# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FF_TagMenuView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FF_TagMenuView
  
  pod 'Masonry'
  pod 'JQCollectionViewAlignLayout'
  pod 'UICollectionViewLeftAlignedLayout'
  

  target 'FF_TagMenuViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FF_TagMenuViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
